"use client";

import Link from "next/link";
import { AlertTriangle, ArrowLeft, Edit3, History, MapPin } from "lucide-react";
import ModuleHeader from "@/components/almacen-desguace/ModuleHeader";
import PhotoManager from "@/components/almacen-desguace/PhotoManager";
import LabelButton from "@/components/almacen-desguace/LabelButton";
import MovementHistory from "@/components/almacen-desguace/MovementHistory";
import RecambioFacilManager from "@/components/almacen-desguace/RecambioFacilManager";
import RecambioFacilLink from "@/components/almacen-desguace/RecambioFacilLink";
import WarehouseLocationLink from "@/components/almacen-desguace/WarehouseLocationLink";
import type { MovimientoUbicacion, PiezaDesguace } from "@/types/almacen-desguace";

export default function PieceDetail({ pieza, movements, publicationError }: { pieza: PiezaDesguace; movements: MovimientoUbicacion[]; publicationError?: string }) {
  const iam = Array.isArray(pieza.iam) ? pieza.iam[0] : pieza.iam;
  const isIam = pieza.tipo_pieza === "IAM";
  return <main className="min-h-screen bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-950"><ModuleHeader title={pieza.codigo_interno} subtitle={pieza.nombre_pieza || "Borrador sin identificar"} /><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6">{publicationError && <section role="alert" className="flex items-start gap-3 rounded-2xl border border-red-500/40 bg-red-500/10 p-4 text-red-100 shadow-lg shadow-red-950/20"><AlertTriangle className="mt-0.5 shrink-0 text-red-400" size={22} /><div><h2 className="font-black">La pieza se ha guardado, pero no se ha publicado en R/F</h2><p className="mt-1 break-words text-sm text-red-200">{publicationError}</p><p className="mt-2 text-xs text-red-300/80">Corrige los datos desde Editar y vuelve a utilizar “Publicar en R/F”.</p></div></section>}<Link href="/almacen-desguace" className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 bg-zinc-900 px-4 py-2.5 text-sm font-bold text-zinc-300 hover:border-amber-500/40 hover:text-amber-300"><ArrowLeft size={17} /> Volver a Almacén Desguace</Link><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded px-2 py-1 text-xs font-black ${isIam ? "bg-violet-500/20 text-violet-300" : "bg-cyan-500/15 text-cyan-300"}`}>{isIam ? "IAM" : "CAT"}</span><p className="font-mono text-sm font-bold text-amber-300">{pieza.codigo_interno}</p></div><h1 className="text-3xl font-black text-white">{pieza.nombre_pieza || "Pieza sin identificar"}</h1></div><div className="flex flex-wrap gap-2">{!isIam && <RecambioFacilLink piece={pieza} />}<LabelButton pieza={pieza} /><Link href={`/almacen-desguace/${pieza.id}/editar`} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2 font-bold text-zinc-950"><Edit3 size={17} /> Editar</Link></div></div>
      <section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5"><div className="flex items-center gap-3"><MapPin className="text-cyan-400" /><div><p className="mb-1.5 text-xs uppercase tracking-wide text-cyan-300/70">Ubicación exacta · pulsa para verla en el plano</p><WarehouseLocationLink location={pieza.ubicacion} />{pieza.ubicacion && <p className="mt-1.5 font-mono text-[11px] text-zinc-500">{pieza.ubicacion}</p>}{pieza.cajon && <p className="mt-1 text-sm text-zinc-400">Dentro del cajón <strong className="text-white">{pieza.cajon.codigo} · {pieza.cajon.nombre}</strong></p>}</div></div>{pieza.cajon && <Link href={`/almacen-desguace/cajones/${pieza.cajon.id}`} className="rounded-xl bg-cyan-500 px-4 py-2.5 font-black text-zinc-950">Abrir cajón</Link>}</section>
      {!isIam && <RecambioFacilManager piece={pieza} />}
      {isIam && iam && <section className="rounded-2xl border border-violet-500/25 bg-violet-500/5 p-5"><h2 className="mb-4 text-lg font-black text-violet-200">Datos específicos IAM</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Line label="Código IAM" value={iam.codigo_iam} mono /><Line label="Cliente R/F" value={iam.idcliente} mono /><Line label="Referencia 2" value={iam.referencia_2} mono /><Line label="Referencia 3" value={iam.referencia_3} mono /><Line label="Marca R/F" value={iam.marca_rf} /><Line label="Familia" value={iam.familia} /><Line label="Precio publicado" value={iam.precio_publicado == null ? null : `${Number(iam.precio_publicado).toFixed(2)} €`} /><Line label="Forma publicación" value={iam.forma_publicacion} /><Line label="Almacén origen" value={iam.almacen_origen} /><Line label="Ubicación origen" value={iam.ubicacion_estanteria_origen} /><Line label="Última entrada" value={iam.fecha_ultima_entrada} /><Line label="Último movimiento" value={iam.fecha_ultimo_movimiento} /><Line label="Peso" value={iam.peso} /><Line label="Largo" value={iam.largo} /><Line label="Ancho" value={iam.ancho} /><Line label="Alto" value={iam.alto} /></div></section>}
      <div className="grid gap-5 lg:grid-cols-3"><Card title="Datos básicos"><Line label="Observaciones" value={pieza.descripcion} /><Line label="Categoría" value={pieza.categoria} /><Line label="Marca pieza" value={pieza.marca_pieza} /><Line label="Procedencia" value={pieza.procedencia} /><Line label="Entrada" value={pieza.fecha_entrada} /></Card><Card title="Referencias"><Line label="Principal" value={pieza.referencia_principal} mono /><Line label="OEM" value={pieza.referencia_oem} mono /><Line label="Equivalentes" value={pieza.referencias_equivalentes} /></Card><Card title="Vehículo compatible"><Line label="Vehículo" value={[pieza.marca_vehiculo, pieza.modelo_vehiculo].filter(Boolean).join(" ")} /><Line label="Matrícula" value={pieza.matricula_vehiculo} mono /><Line label="Motorización" value={pieza.motorizacion} /><Line label="Código motor" value={pieza.codigo_motor} mono /><Line label="Años" value={pieza.ano_desde || pieza.ano_hasta ? `${pieza.ano_desde || "?"} – ${pieza.ano_hasta || "?"}` : null} /></Card></div>
      <section className="grid gap-3 rounded-2xl border border-zinc-800 bg-zinc-900 p-5 sm:grid-cols-2 lg:grid-cols-6"><Stat label="Estado" value={pieza.estado_pieza} /><Stat label="Cantidad" value={pieza.cantidad} /><Stat label="Precio venta" value={pieza.precio_venta == null ? null : `${Number(pieza.precio_venta).toFixed(2)} €`} /><Stat label="Precio coste" value={pieza.precio_coste == null ? null : `${Number(pieza.precio_coste).toFixed(2)} €`} /><Stat label="Proceso" value={pieza.estado_proceso} /><Stat label="Online" value={pieza.publicado_online ? "Sí" : "No"} /></section>
      <section className="rounded-2xl border border-zinc-800 bg-zinc-950/40 p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><History className="text-cyan-400" size={20} /><div><h2 className="font-bold text-white">Historial de ubicación</h2><p className="text-xs text-zinc-500">Colocaciones, traslados e incidencias de esta pieza</p></div></div><Link href="/almacen-desguace/historial" className="text-sm font-bold text-cyan-300 hover:text-cyan-200">Ver historial completo</Link></div><MovementHistory movements={movements} compact /></section>
      <PhotoManager piezaId={pieza.id} initialPhotos={pieza.fotos || []} />
    </div></main>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><h2 className="mb-4 font-bold text-white">{title}</h2><div className="space-y-3">{children}</div></section>; }
function Line({ label, value, mono }: { label: string; value: unknown; mono?: boolean }) { return <div><p className="text-xs text-zinc-500">{label}</p><p className={`text-sm text-zinc-200 ${mono ? "font-mono" : ""}`}>{String(value || "-")}</p></div>; }
function Stat({ label, value }: { label: string; value: unknown }) { return <div><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-bold text-white">{value === null || value === undefined || value === "" ? "-" : String(value)}</p></div>; }
