import packageMetadata from "@/package.json";

export const APP_VERSION = packageMetadata.version;

export const APP_CHANGELOG = [
  {
    version: "1.3.0",
    date: "18 de agosto de 2026",
    changes: [
      "Nuevo panel resumen con avisos y accesos directos para organizar el almacén.",
      "Actividad reciente más compacta para entradas, ventas y retiradas.",
      "Sistema de ventas con fecha, empleado, precio final, forma de pago y observaciones.",
      "Liberación automática de ubicaciones y posibilidad de deshacer ventas accidentales.",
      "Resumen de facturación, base imponible, IVA, coste y margen estimado.",
      "Filtros y detalles mejorados en la pestaña de piezas vendidas.",
      "Gestión persistente de empleados activos e inactivos.",
      "Historial de cada pieza presentado como una línea temporal.",
      "Copias de seguridad y papelera para recuperar piezas eliminadas.",
      "Retiradas trasladadas a una sección secundaria.",
      "Navegación superior permanente en ordenador y mejoras del menú móvil.",
      "Pantallas de carga para Historial, Plano, estanterías, huecos y cajones.",
      "Plano más compacto y coherente con el diseño general.",
      "Resaltado de estantería, nivel y hueco exactos de cada ubicación.",
      "Controles para quitar el zoom, centrar la ubicación y mostrar todas las estanterías.",
      "Alta manual de piezas IAM sin conocer su código interno de Recambio Fácil.",
      "Mejoras generales de filtros, ventanas, adaptación móvil y rendimiento.",
    ],
  },
  {
    version: "1.2.1",
    date: "7 de agosto de 2026",
    changes: [
      "Piezas IAM almacenadas junto a las CAT e identificadas por su tipo.",
      "Importación IAM desde la API de Recambio Fácil y desde CSV con vista previa.",
      "Reimportación de IAM sin duplicados.",
      "Filtros CAT e IAM y ficha con los datos específicos de cada pieza IAM.",
      "Protección frente a publicaciones IAM accidentales mediante el endpoint CAT.",
      "Acceso directo a las piezas IAM publicadas en Recambio Fácil.",
    ],
  },
  {
    version: "1.1.1",
    date: "5 de agosto de 2026",
    changes: [
      "Ficha dinámica y etiqueta QR para cada estantería.",
      "Detalle de ocupación, niveles, huecos, piezas y cajones de la estantería.",
      "El aviso de código leído desaparece automáticamente.",
      "Las piezas de un cajón se pueden marcar como vendidas desde el propio cajón.",
      "Vistas previas fieles para elegir el formato de las etiquetas.",
      "Diseño real de impresión con el código de barras definitivo.",
      "Corrección de textos recortados y solapados en las etiquetas.",
      "Acciones individuales de las piezas reorganizadas en un orden más directo.",
      "Impresión de etiquetas disponible desde la lista de piezas.",
      "Historial de novedades accesible pulsando el número de versión.",
      "Selector visual al imprimir etiquetas de piezas.",
      "Formato normal de 62 × 42 mm.",
      "Formato compacto de 62 × 30 mm para piezas pequeñas.",
      "La aplicación recuerda el último formato utilizado.",
      "Primera versión estable de Almacén Desguace.",
      "Gestión de piezas, estanterías, niveles, huecos y cajones.",
      "Plano general, historial y localización visual.",
      "Integración de publicación y gestión con Recambio Fácil.",
      "Etiquetas de piezas con código de barras y etiquetas QR para cajones.",
      "Optimización y subida múltiple de fotografías compatibles con Recambio Fácil.",
    ],
  },
] as const;
