"use client";

import Link from "next/link";
import { ArrowLeft, Check, Loader2 } from "lucide-react";

export function SettingsShell({ title, subtitle, icon, children }: { title: string; subtitle: string; icon: React.ReactNode; children: React.ReactNode }) { return <main className="min-h-dvh bg-zinc-950 p-4 text-white"><div className="mx-auto max-w-2xl"><header className="mb-6 flex items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-black">{icon}{title}</h1><p className="mt-1 text-sm text-zinc-400">{subtitle}</p></div><Link href="/admin/configuracion" className="flex min-h-11 items-center gap-2 rounded-xl border border-zinc-700 px-3 text-sm font-bold text-zinc-300"><ArrowLeft size={17} /> Configuración</Link></header>{children}</div></main>; }
export function OptionGroup({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="mb-2 px-1 text-sm font-black uppercase tracking-wide text-zinc-500">{title}</h2><div className="divide-y divide-zinc-800 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900">{children}</div></section>; }
export function Toggle({ title, description, checked, disabled, onClick }: { title: string; description: string; checked: boolean; disabled?: boolean; onClick: () => void }) { return <button disabled={disabled} onClick={onClick} className="flex min-h-20 w-full items-center gap-4 p-4 text-left disabled:opacity-35"><span className="min-w-0 flex-1"><strong className="block text-base text-white">{title}</strong><span className="mt-1 block text-xs leading-5 text-zinc-500">{description}</span></span><span aria-label={checked ? "Activado" : "Desactivado"} className={`relative h-8 w-14 shrink-0 rounded-full transition-colors ${checked ? "bg-cyan-400" : "bg-zinc-700"}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white shadow transition-transform ${checked ? "translate-x-7" : "translate-x-1"}`} /></span></button>; }
export function Message({ tone, children }: { tone: "error" | "saved"; children: React.ReactNode }) { return <p className={`mb-4 flex gap-2 rounded-xl border p-3 text-sm font-bold ${tone === "error" ? "border-red-500/30 bg-red-500/10 text-red-300" : "border-emerald-500/30 bg-emerald-500/10 text-emerald-300"}`}>{tone === "saved" && <Check size={18} />}{children}</p>; }
export function Loading() { return <div className="flex justify-center py-20"><Loader2 className="animate-spin text-cyan-400" /></div>; }
export function SaveButton({ saving, onClick }: { saving: boolean; onClick: () => void }) { return <button onClick={onClick} disabled={saving} className="sticky bottom-4 mt-6 flex min-h-16 w-full items-center justify-center gap-2 rounded-2xl bg-cyan-400 text-lg font-black text-zinc-950 shadow-xl disabled:opacity-60">{saving && <Loader2 className="animate-spin" />} Guardar cambios</button>; }
