-- Organización física guiada del Almacén Desguace.
create table if not exists public.almacen_desguace_estanterias (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  descripcion text,
  categorias text[] not null default '{}',
  palabras_clave text[] not null default '{}',
  niveles integer not null default 1,
  huecos_por_nivel integer not null default 1,
  capacidad_maxima integer not null default 1,
  llena_manual boolean not null default false,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint almacen_desguace_estanteria_codigo_check
    check (codigo ~ '^E[0-9]{2}$'),
  constraint almacen_desguace_estanteria_dimensiones_check
    check (
      niveles between 1 and 99
      and huecos_por_nivel between 1 and 99
      and capacidad_maxima between 1 and niveles * huecos_por_nivel
    )
);

create table if not exists public.almacen_desguace_ubicaciones_movimientos (
  id bigint generated by default as identity primary key,
  pieza_id bigint not null references public.almacen_desguace_piezas(id) on delete cascade,
  estanteria_sugerida_id bigint references public.almacen_desguace_estanterias(id) on delete set null,
  ubicacion_sugerida text,
  resultado text not null,
  ubicacion_final text,
  motivo text,
  created_at timestamptz not null default now(),
  constraint almacen_desguace_movimiento_resultado_check check (
    resultado in ('colocada_sugerida', 'colocada_alternativa', 'no_colocada')
  ),
  constraint almacen_desguace_movimiento_ubicaciones_check check (
    (ubicacion_sugerida is null or ubicacion_sugerida ~ '^DESGUACE-E[0-9]{2}-N[0-9]{2}-C[0-9]{2}$')
    and (ubicacion_final is null or ubicacion_final ~ '^DESGUACE-E[0-9]{2}-N[0-9]{2}-C[0-9]{2}$')
  ),
  constraint almacen_desguace_movimiento_confirmacion_check check (
    (resultado = 'no_colocada' and ubicacion_final is null and nullif(btrim(motivo), '') is not null)
    or (resultado in ('colocada_sugerida', 'colocada_alternativa') and ubicacion_final is not null)
  )
);

create index if not exists almacen_desguace_movimientos_pieza_idx
  on public.almacen_desguace_ubicaciones_movimientos (pieza_id, created_at desc);
create unique index if not exists almacen_desguace_ubicacion_unica_idx
  on public.almacen_desguace_piezas (ubicacion)
  where ubicacion is not null and btrim(ubicacion) <> '';

drop trigger if exists almacen_desguace_estanterias_updated_at
  on public.almacen_desguace_estanterias;
create trigger almacen_desguace_estanterias_updated_at
before update on public.almacen_desguace_estanterias
for each row execute function public.almacen_desguace_set_updated_at();

alter table public.almacen_desguace_estanterias enable row level security;
alter table public.almacen_desguace_ubicaciones_movimientos enable row level security;

drop policy if exists "API desguace estanterias" on public.almacen_desguace_estanterias;
create policy "API desguace estanterias" on public.almacen_desguace_estanterias
  for all to anon, authenticated using (true) with check (true);
drop policy if exists "API desguace ubicaciones movimientos" on public.almacen_desguace_ubicaciones_movimientos;
create policy "API desguace ubicaciones movimientos" on public.almacen_desguace_ubicaciones_movimientos
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.almacen_desguace_estanterias to anon, authenticated;
grant select, insert, update, delete on public.almacen_desguace_ubicaciones_movimientos to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_estanterias_id_seq to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_ubicaciones_movimientos_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
