-- Seguridad y trazabilidad de herramientas comunes.
-- IMPORTANTE: configurar SUPABASE_SERVICE_ROLE_KEY en el servidor antes de
-- ejecutar esta migración. Después de aplicarla, la clave anónima queda en
-- modo de solo acceso a través de las APIs protegidas de la aplicación.

alter table public.herramientas_comunes_herramientas
  add column if not exists qr_token uuid default gen_random_uuid();

update public.herramientas_comunes_herramientas
set qr_token = gen_random_uuid()
where qr_token is null;

alter table public.herramientas_comunes_herramientas
  alter column qr_token set default gen_random_uuid(),
  alter column qr_token set not null;

create unique index if not exists herramientas_comunes_qr_token_uidx
  on public.herramientas_comunes_herramientas (qr_token);

create table if not exists public.herramientas_comunes_fotos (
  id bigint generated by default as identity primary key,
  herramienta_id bigint not null references public.herramientas_comunes_herramientas(id) on delete cascade,
  url text not null,
  storage_path text,
  tipo text not null check (tipo in ('inicial', 'actualizacion')),
  created_at timestamptz not null default now()
);

create index if not exists herramientas_comunes_fotos_herramienta_idx
  on public.herramientas_comunes_fotos (herramienta_id, created_at asc);

insert into public.herramientas_comunes_fotos (herramienta_id, url, tipo)
select herramienta.id, herramienta.foto_url, 'inicial'
from public.herramientas_comunes_herramientas herramienta
where herramienta.foto_url is not null
  and not exists (
    select 1 from public.herramientas_comunes_fotos foto
    where foto.herramienta_id = herramienta.id
  );

-- El estado reparación ya no forma parte del funcionamiento solicitado.
update public.herramientas_comunes_herramientas
set estado = 'perdida', empleado_actual = null, vehiculo_actual = null, retirada_at = null
where estado = 'reparacion';

update public.herramientas_comunes_movimientos
set estado_anterior = 'perdida'
where estado_anterior = 'reparacion';

update public.herramientas_comunes_movimientos
set estado_nuevo = 'perdida'
where estado_nuevo = 'reparacion';

alter table public.herramientas_comunes_herramientas
  drop constraint if exists herramientas_comunes_herramientas_estado_check;
alter table public.herramientas_comunes_herramientas
  add constraint herramientas_comunes_herramientas_estado_check
  check (estado in ('disponible', 'prestada', 'perdida'));

alter table public.herramientas_comunes_movimientos
  drop constraint if exists herramientas_comunes_movimientos_estado_anterior_check;
alter table public.herramientas_comunes_movimientos
  add constraint herramientas_comunes_movimientos_estado_anterior_check
  check (estado_anterior is null or estado_anterior in ('disponible', 'prestada', 'perdida'));

alter table public.herramientas_comunes_movimientos
  drop constraint if exists herramientas_comunes_movimientos_estado_nuevo_check;
alter table public.herramientas_comunes_movimientos
  add constraint herramientas_comunes_movimientos_estado_nuevo_check
  check (estado_nuevo in ('disponible', 'prestada', 'perdida'));

-- Retirada, devolución y cambio de estado se guardan junto con su movimiento
-- dentro de una única transacción de PostgreSQL.
create or replace function public.herramientas_comunes_cambiar_estado(
  p_herramienta_id bigint,
  p_accion text,
  p_empleado text default null,
  p_vehiculo text default null,
  p_estado_nuevo text default null
)
returns public.herramientas_comunes_herramientas
language plpgsql
security definer
set search_path = public
as $$
declare
  anterior public.herramientas_comunes_herramientas%rowtype;
  actualizada public.herramientas_comunes_herramientas%rowtype;
  empleado_limpio text := nullif(btrim(coalesce(p_empleado, '')), '');
  vehiculo_limpio text := nullif(btrim(coalesce(p_vehiculo, '')), '');
begin
  select * into anterior
  from public.herramientas_comunes_herramientas
  where id = p_herramienta_id
  for update;

  if not found then raise exception 'Herramienta no encontrada.'; end if;

  if p_accion = 'retirar' then
    if anterior.estado <> 'disponible' then raise exception 'La herramienta ya no está disponible.'; end if;
    if empleado_limpio is null then raise exception 'Selecciona el empleado que la retira.'; end if;
    update public.herramientas_comunes_herramientas
    set estado = 'prestada', empleado_actual = empleado_limpio,
        vehiculo_actual = vehiculo_limpio, retirada_at = now()
    where id = anterior.id returning * into actualizada;
    insert into public.herramientas_comunes_movimientos
      (herramienta_id, tipo, empleado, vehiculo, estado_anterior, estado_nuevo)
    values (anterior.id, 'retirada', empleado_limpio, vehiculo_limpio, anterior.estado, 'prestada');
  elsif p_accion = 'devolver' then
    if anterior.estado <> 'prestada' then raise exception 'La herramienta no figura como prestada.'; end if;
    empleado_limpio := coalesce(empleado_limpio, anterior.empleado_actual);
    if empleado_limpio is null then raise exception 'Selecciona el empleado que la coloca.'; end if;
    update public.herramientas_comunes_herramientas
    set estado = 'disponible', empleado_actual = null,
        vehiculo_actual = null, retirada_at = null
    where id = anterior.id returning * into actualizada;
    insert into public.herramientas_comunes_movimientos
      (herramienta_id, tipo, empleado, vehiculo, estado_anterior, estado_nuevo)
    values (anterior.id, 'devolucion', empleado_limpio, anterior.vehiculo_actual, anterior.estado, 'disponible');
  elsif p_accion = 'estado' then
    if p_estado_nuevo not in ('disponible', 'perdida') then raise exception 'Estado no válido.'; end if;
    update public.herramientas_comunes_herramientas
    set estado = p_estado_nuevo, empleado_actual = null,
        vehiculo_actual = null, retirada_at = null
    where id = anterior.id returning * into actualizada;
    insert into public.herramientas_comunes_movimientos
      (herramienta_id, tipo, empleado, vehiculo, estado_anterior, estado_nuevo)
    values (anterior.id, 'cambio_estado', empleado_limpio, anterior.vehiculo_actual, anterior.estado, p_estado_nuevo);
  else
    raise exception 'Acción no válida.';
  end if;

  return actualizada;
end;
$$;

revoke all on function public.herramientas_comunes_cambiar_estado(bigint, text, text, text, text) from public, anon, authenticated;
grant execute on function public.herramientas_comunes_cambiar_estado(bigint, text, text, text, text) to service_role;

-- Cierre de acceso directo. Las APIs del servidor usan service_role y siguen
-- exigiendo la sesión privada de Cazapiezas.
drop policy if exists "API herramientas estanterias" on public.herramientas_comunes_estanterias;
drop policy if exists "API herramientas" on public.herramientas_comunes_herramientas;
drop policy if exists "API herramientas movimientos" on public.herramientas_comunes_movimientos;

alter table public.herramientas_comunes_fotos enable row level security;
alter table public.herramientas_comunes_estanterias force row level security;
alter table public.herramientas_comunes_herramientas force row level security;
alter table public.herramientas_comunes_movimientos force row level security;
alter table public.herramientas_comunes_fotos force row level security;

revoke all on public.herramientas_comunes_estanterias from anon, authenticated;
revoke all on public.herramientas_comunes_herramientas from anon, authenticated;
revoke all on public.herramientas_comunes_movimientos from anon, authenticated;
revoke all on public.herramientas_comunes_fotos from anon, authenticated;
revoke all on sequence public.herramientas_comunes_codigo_seq from anon, authenticated;
revoke all on sequence public.herramientas_comunes_estanterias_id_seq from anon, authenticated;
revoke all on sequence public.herramientas_comunes_herramientas_id_seq from anon, authenticated;
revoke all on sequence public.herramientas_comunes_movimientos_id_seq from anon, authenticated;
revoke all on sequence public.herramientas_comunes_fotos_id_seq from anon, authenticated;

grant select, insert, update, delete on public.herramientas_comunes_estanterias to service_role;
grant select, insert, update, delete on public.herramientas_comunes_herramientas to service_role;
grant select, insert on public.herramientas_comunes_movimientos to service_role;
grant select, insert, update, delete on public.herramientas_comunes_fotos to service_role;
grant usage, select on sequence public.herramientas_comunes_codigo_seq to service_role;
grant usage, select on sequence public.herramientas_comunes_estanterias_id_seq to service_role;
grant usage, select on sequence public.herramientas_comunes_herramientas_id_seq to service_role;
grant usage, select on sequence public.herramientas_comunes_movimientos_id_seq to service_role;
grant usage, select on sequence public.herramientas_comunes_fotos_id_seq to service_role;

notify pgrst, 'reload schema';
