-- Modulo independiente ALMACEN DESGUACE. No modifica las tablas de stock.
create sequence if not exists public.almacen_desguace_codigo_seq start 1;

create table if not exists public.almacen_desguace_piezas (
  id bigint generated by default as identity primary key,
  codigo_interno text not null unique default
    ('CZP-DESGUACE-' || lpad(nextval('public.almacen_desguace_codigo_seq')::text, 6, '0')),
  nombre_pieza text,
  descripcion text,
  categoria text,
  marca_pieza text,
  referencia_principal text,
  referencia_oem text,
  referencias_equivalentes text,
  marca_vehiculo text,
  modelo_vehiculo text,
  motorizacion text,
  codigo_motor text,
  ano_desde smallint,
  ano_hasta smallint,
  estado_pieza text,
  cantidad integer,
  precio_coste numeric(12, 2),
  precio_venta numeric(12, 2),
  ubicacion text,
  procedencia text,
  estado_proceso text not null default 'Pendiente de identificar',
  publicado_online boolean not null default false,
  fecha_entrada date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint almacen_desguace_estado_pieza_check check (
    estado_pieza is null or estado_pieza in (
      'Nueva', 'Nueva con embalaje abierto', 'Segunda mano comprobada',
      'Segunda mano sin comprobar', 'Con defecto', 'Pendiente de revisar',
      'No apta para venta'
    )
  ),
  constraint almacen_desguace_estado_proceso_check check (estado_proceso in (
    'Pendiente de identificar', 'Pendiente de comprobar', 'Pendiente de fotografiar',
    'Lista para publicar', 'Publicada', 'Reservada', 'Vendida',
    'Pendiente de envío', 'Enviada', 'Devuelta', 'Retirada'
  )),
  constraint almacen_desguace_cantidad_check check (cantidad is null or cantidad >= 0),
  constraint almacen_desguace_precios_check check (
    (precio_coste is null or precio_coste >= 0) and
    (precio_venta is null or precio_venta >= 0)
  ),
  constraint almacen_desguace_anos_check check (
    ano_desde is null or ano_hasta is null or ano_hasta >= ano_desde
  ),
  constraint almacen_desguace_ubicacion_formato_check check (
    ubicacion is null or ubicacion ~ '^DESGUACE-E[0-9]{2}-N[0-9]{2}-C[0-9]{2}$'
  ),
  constraint almacen_desguace_disponible_ubicado_check check (
    estado_proceso not in ('Lista para publicar', 'Publicada')
    or ubicacion is not null
  ),
  constraint almacen_desguace_publicable_completo_check check (
    estado_proceso not in ('Lista para publicar', 'Publicada')
    or (
      nullif(btrim(nombre_pieza), '') is not null
      and (nullif(btrim(referencia_principal), '') is not null or nullif(btrim(referencia_oem), '') is not null)
      and estado_pieza is not null
      and precio_venta is not null
      and ubicacion is not null
      and cantidad is not null
    )
  )
);

create table if not exists public.almacen_desguace_fotos (
  id bigint generated by default as identity primary key,
  pieza_id bigint not null references public.almacen_desguace_piezas(id) on delete cascade,
  url_imagen text not null,
  es_principal boolean not null default false,
  orden integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists almacen_desguace_codigo_idx
  on public.almacen_desguace_piezas (codigo_interno);
create index if not exists almacen_desguace_referencia_idx
  on public.almacen_desguace_piezas (referencia_principal);
create index if not exists almacen_desguace_ubicacion_idx
  on public.almacen_desguace_piezas (ubicacion);
create index if not exists almacen_desguace_proceso_idx
  on public.almacen_desguace_piezas (estado_proceso);
create index if not exists almacen_desguace_fotos_pieza_idx
  on public.almacen_desguace_fotos (pieza_id, orden);
create unique index if not exists almacen_desguace_foto_principal_idx
  on public.almacen_desguace_fotos (pieza_id) where es_principal;

create or replace function public.almacen_desguace_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists almacen_desguace_updated_at on public.almacen_desguace_piezas;
create trigger almacen_desguace_updated_at
before update on public.almacen_desguace_piezas
for each row execute function public.almacen_desguace_set_updated_at();

alter table public.almacen_desguace_piezas enable row level security;
alter table public.almacen_desguace_fotos enable row level security;

drop policy if exists "API desguace piezas" on public.almacen_desguace_piezas;
create policy "API desguace piezas" on public.almacen_desguace_piezas
  for all to anon, authenticated using (true) with check (true);
drop policy if exists "API desguace fotos" on public.almacen_desguace_fotos;
create policy "API desguace fotos" on public.almacen_desguace_fotos
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.almacen_desguace_piezas to anon, authenticated;
grant select, insert, update, delete on public.almacen_desguace_fotos to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_codigo_seq to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_piezas_id_seq to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_fotos_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'almacen-desguace', 'almacen-desguace', true, 10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "API fotos almacen desguace" on storage.objects;
create policy "API fotos almacen desguace" on storage.objects
  for all to anon, authenticated
  using (bucket_id = 'almacen-desguace')
  with check (bucket_id = 'almacen-desguace');
