-- Herramientas y maletines compartidos del taller.
create sequence if not exists public.herramientas_comunes_codigo_seq start 1;

create table if not exists public.herramientas_comunes_estanterias (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  zona text not null,
  niveles integer not null default 5 check (niveles between 1 and 30),
  orden integer not null default 0,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.herramientas_comunes_herramientas (
  id bigint generated by default as identity primary key,
  codigo text not null unique default ('HT-' || lpad(nextval('public.herramientas_comunes_codigo_seq')::text, 4, '0')),
  nombre text not null,
  categoria text,
  marca text,
  descripcion text,
  foto_url text,
  estanteria_id bigint not null references public.herramientas_comunes_estanterias(id),
  nivel integer not null check (nivel between 1 and 30),
  posicion text not null,
  estado text not null default 'disponible' check (estado in ('disponible', 'prestada', 'reparacion', 'perdida')),
  empleado_actual text,
  vehiculo_actual text,
  retirada_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint herramientas_comunes_prestamo_check check (
    (estado = 'prestada' and nullif(btrim(empleado_actual), '') is not null and retirada_at is not null)
    or estado <> 'prestada'
  )
);

create table if not exists public.herramientas_comunes_movimientos (
  id bigint generated by default as identity primary key,
  herramienta_id bigint not null references public.herramientas_comunes_herramientas(id) on delete cascade,
  tipo text not null check (tipo in ('alta', 'retirada', 'devolucion', 'cambio_estado', 'cambio_ubicacion')),
  empleado text,
  vehiculo text,
  estado_anterior text check (estado_anterior is null or estado_anterior in ('disponible', 'prestada', 'reparacion', 'perdida')),
  estado_nuevo text not null check (estado_nuevo in ('disponible', 'prestada', 'reparacion', 'perdida')),
  detalle text,
  created_at timestamptz not null default now()
);

create index if not exists herramientas_comunes_estado_idx on public.herramientas_comunes_herramientas (estado);
create index if not exists herramientas_comunes_ubicacion_idx on public.herramientas_comunes_herramientas (estanteria_id, nivel);
create index if not exists herramientas_comunes_movimientos_idx on public.herramientas_comunes_movimientos (herramienta_id, created_at desc);

create or replace function public.herramientas_comunes_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists herramientas_comunes_estanterias_updated_at on public.herramientas_comunes_estanterias;
create trigger herramientas_comunes_estanterias_updated_at before update on public.herramientas_comunes_estanterias
for each row execute function public.herramientas_comunes_set_updated_at();
drop trigger if exists herramientas_comunes_herramientas_updated_at on public.herramientas_comunes_herramientas;
create trigger herramientas_comunes_herramientas_updated_at before update on public.herramientas_comunes_herramientas
for each row execute function public.herramientas_comunes_set_updated_at();

insert into public.herramientas_comunes_estanterias (codigo, nombre, zona, niveles, orden) values
  ('T01', 'Estantería 1', 'Taller', 5, 1),
  ('T02', 'Estantería 2', 'Taller', 5, 2),
  ('T03', 'Estantería 3', 'Taller', 5, 3),
  ('A01', 'Estantería 4', 'Zona auxiliar', 5, 4),
  ('A02', 'Estantería 5', 'Zona auxiliar', 5, 5)
on conflict (codigo) do nothing;

alter table public.herramientas_comunes_estanterias enable row level security;
alter table public.herramientas_comunes_herramientas enable row level security;
alter table public.herramientas_comunes_movimientos enable row level security;

drop policy if exists "API herramientas estanterias" on public.herramientas_comunes_estanterias;
create policy "API herramientas estanterias" on public.herramientas_comunes_estanterias for all to anon, authenticated using (true) with check (true);
drop policy if exists "API herramientas" on public.herramientas_comunes_herramientas;
create policy "API herramientas" on public.herramientas_comunes_herramientas for all to anon, authenticated using (true) with check (true);
drop policy if exists "API herramientas movimientos" on public.herramientas_comunes_movimientos;
create policy "API herramientas movimientos" on public.herramientas_comunes_movimientos for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.herramientas_comunes_estanterias to anon, authenticated;
grant select, insert, update, delete on public.herramientas_comunes_herramientas to anon, authenticated;
grant select, insert on public.herramientas_comunes_movimientos to anon, authenticated;
grant usage, select on sequence public.herramientas_comunes_codigo_seq to anon, authenticated;
grant usage, select on sequence public.herramientas_comunes_estanterias_id_seq to anon, authenticated;
grant usage, select on sequence public.herramientas_comunes_herramientas_id_seq to anon, authenticated;
grant usage, select on sequence public.herramientas_comunes_movimientos_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
