-- Cajones con varias piezas dentro de un único hueco físico.
create sequence if not exists public.almacen_desguace_cajon_codigo_seq start 1;

create table if not exists public.almacen_desguace_cajones (
  id bigint generated by default as identity primary key,
  codigo text not null unique default ('CAJ-' || lpad(nextval('public.almacen_desguace_cajon_codigo_seq')::text, 4, '0')),
  nombre text not null,
  descripcion text,
  ubicacion text not null unique,
  capacidad_maxima integer not null default 20,
  lleno_manual boolean not null default false,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint almacen_desguace_cajon_codigo_check check (codigo ~ '^CAJ-[0-9]{4,}$'),
  constraint almacen_desguace_cajon_ubicacion_check check (ubicacion ~ '^DESGUACE-E[0-9]{2}-N[0-9]{2}-C[0-9]{2}$'),
  constraint almacen_desguace_cajon_capacidad_check check (capacidad_maxima between 1 and 9999)
);

alter table public.almacen_desguace_piezas
  add column if not exists cajon_id bigint references public.almacen_desguace_cajones(id) on delete restrict,
  add column if not exists matricula_vehiculo text;

drop index if exists public.almacen_desguace_ubicacion_unica_idx;
create unique index if not exists almacen_desguace_ubicacion_directa_unica_idx
  on public.almacen_desguace_piezas (ubicacion)
  where cajon_id is null and ubicacion is not null and btrim(ubicacion) <> '';
create index if not exists almacen_desguace_piezas_cajon_idx on public.almacen_desguace_piezas (cajon_id);
create index if not exists almacen_desguace_piezas_matricula_idx on public.almacen_desguace_piezas (matricula_vehiculo);

create table if not exists public.almacen_desguace_cajones_movimientos (
  id bigint generated by default as identity primary key,
  cajon_id bigint not null references public.almacen_desguace_cajones(id) on delete cascade,
  pieza_id bigint references public.almacen_desguace_piezas(id) on delete set null,
  tipo_movimiento text not null,
  ubicacion_anterior text,
  ubicacion_final text,
  detalle text,
  usuario_nombre text not null default 'Usuario de almacén',
  created_at timestamptz not null default now(),
  constraint almacen_desguace_cajon_movimiento_tipo_check check (tipo_movimiento in ('creacion', 'entrada', 'salida', 'traslado', 'estado'))
);
create index if not exists almacen_desguace_cajon_movimientos_fecha_idx
  on public.almacen_desguace_cajones_movimientos (cajon_id, created_at desc);

create or replace function public.almacen_desguace_validar_cajon()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if exists (select 1 from public.almacen_desguace_piezas where ubicacion = new.ubicacion and cajon_id is null) then
    raise exception 'El hueco % ya está ocupado por una pieza.', new.ubicacion;
  end if;
  if exists (
    select 1 from public.almacen_desguace_piezas
    where cajon_id = new.id
    group by cajon_id having count(*) > new.capacidad_maxima
  ) then
    raise exception 'La capacidad no puede ser menor que el número de piezas actuales.';
  end if;
  return new;
end;
$$;
drop trigger if exists almacen_desguace_validar_cajon_trigger on public.almacen_desguace_cajones;
create trigger almacen_desguace_validar_cajon_trigger
before insert or update of ubicacion, capacidad_maxima on public.almacen_desguace_cajones
for each row execute function public.almacen_desguace_validar_cajon();

create or replace function public.almacen_desguace_preparar_pieza_cajon()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  cajon_record public.almacen_desguace_cajones%rowtype;
  piezas_actuales integer;
begin
  if new.cajon_id is not null then
    select * into cajon_record from public.almacen_desguace_cajones where id = new.cajon_id;
    if not found then raise exception 'El cajón indicado no existe.'; end if;
    if not cajon_record.activo then raise exception 'El cajón % está inactivo.', cajon_record.codigo; end if;
    if tg_op = 'INSERT' or old.cajon_id is distinct from new.cajon_id then
      select count(*) into piezas_actuales from public.almacen_desguace_piezas
      where cajon_id = new.cajon_id and (tg_op = 'INSERT' or id <> new.id);
      if cajon_record.lleno_manual or piezas_actuales >= cajon_record.capacidad_maxima then
        raise exception 'El cajón % está lleno.', cajon_record.codigo;
      end if;
    end if;
    new.ubicacion := cajon_record.ubicacion;
  else
    if tg_op = 'UPDATE' and old.cajon_id is not null and new.ubicacion is not distinct from old.ubicacion then
      new.ubicacion := null;
    end if;
    if new.ubicacion is not null and exists (select 1 from public.almacen_desguace_cajones where ubicacion = new.ubicacion) then
      raise exception 'Ese hueco está ocupado por un cajón.';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists almacen_desguace_preparar_pieza_cajon_trigger on public.almacen_desguace_piezas;
create trigger almacen_desguace_preparar_pieza_cajon_trigger
before insert or update of cajon_id, ubicacion on public.almacen_desguace_piezas
for each row execute function public.almacen_desguace_preparar_pieza_cajon();

create or replace function public.almacen_desguace_historial_contenido_cajon()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.cajon_id is not null and old.cajon_id is distinct from new.cajon_id then
    insert into public.almacen_desguace_cajones_movimientos (cajon_id, pieza_id, tipo_movimiento, ubicacion_anterior, detalle)
    values (old.cajon_id, new.id, 'salida', old.ubicacion, 'Pieza retirada del cajón');
  end if;
  if new.cajon_id is not null and old.cajon_id is distinct from new.cajon_id then
    insert into public.almacen_desguace_cajones_movimientos (cajon_id, pieza_id, tipo_movimiento, ubicacion_final, detalle)
    values (new.cajon_id, new.id, 'entrada', new.ubicacion, 'Pieza añadida al cajón');
  end if;
  return new;
end;
$$;
drop trigger if exists almacen_desguace_historial_contenido_cajon_trigger on public.almacen_desguace_piezas;
create trigger almacen_desguace_historial_contenido_cajon_trigger
after update of cajon_id on public.almacen_desguace_piezas
for each row execute function public.almacen_desguace_historial_contenido_cajon();

create or replace function public.almacen_desguace_historial_cajon()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.almacen_desguace_cajones_movimientos (cajon_id, tipo_movimiento, ubicacion_final, detalle)
    values (new.id, 'creacion', new.ubicacion, 'Cajón creado');
    return new;
  end if;
  if old.ubicacion is distinct from new.ubicacion then
    update public.almacen_desguace_piezas set ubicacion = new.ubicacion where cajon_id = new.id;
    insert into public.almacen_desguace_cajones_movimientos (cajon_id, tipo_movimiento, ubicacion_anterior, ubicacion_final, detalle)
    values (new.id, 'traslado', old.ubicacion, new.ubicacion, 'Cajón trasladado con todo su contenido');
  end if;
  if old.lleno_manual is distinct from new.lleno_manual then
    insert into public.almacen_desguace_cajones_movimientos (cajon_id, tipo_movimiento, ubicacion_final, detalle)
    values (new.id, 'estado', new.ubicacion, case when new.lleno_manual then 'Marcado manualmente como lleno' else 'Marcado con espacio disponible' end);
  end if;
  return new;
end;
$$;
drop trigger if exists almacen_desguace_historial_cajon_trigger on public.almacen_desguace_cajones;
create trigger almacen_desguace_historial_cajon_trigger
after insert or update of ubicacion, lleno_manual on public.almacen_desguace_cajones
for each row execute function public.almacen_desguace_historial_cajon();

drop trigger if exists almacen_desguace_cajones_updated_at on public.almacen_desguace_cajones;
create trigger almacen_desguace_cajones_updated_at before update on public.almacen_desguace_cajones
for each row execute function public.almacen_desguace_set_updated_at();

alter table public.almacen_desguace_cajones enable row level security;
alter table public.almacen_desguace_cajones_movimientos enable row level security;
create policy "API desguace cajones" on public.almacen_desguace_cajones for all to anon, authenticated using (true) with check (true);
create policy "API desguace cajones movimientos" on public.almacen_desguace_cajones_movimientos for all to anon, authenticated using (true) with check (true);
grant select, insert, update, delete on public.almacen_desguace_cajones to anon, authenticated;
grant select, insert, update, delete on public.almacen_desguace_cajones_movimientos to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_cajon_codigo_seq to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_cajones_id_seq to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_cajones_movimientos_id_seq to anon, authenticated;
notify pgrst, 'reload schema';
