-- Distribución visual editable del plano del Almacén Desguace.
-- Esta tabla no modifica ubicaciones, piezas, cajones ni historiales.

create table if not exists public.almacen_desguace_plano_elementos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  codigo_estanteria text,
  nombre text not null default '',
  x numeric(8,2) not null,
  y numeric(8,2) not null,
  ancho numeric(8,2) not null,
  alto numeric(8,2) not null,
  rotacion integer not null default 0,
  color text not null default '#64748b',
  orden integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint almacen_desguace_plano_tipo_check
    check (tipo in ('estanteria', 'zona_suelo')),
  constraint almacen_desguace_plano_codigo_check
    check (
      (tipo = 'estanteria' and codigo_estanteria ~ '^E[0-9]{2}$')
      or (tipo = 'zona_suelo' and codigo_estanteria is null)
    ),
  constraint almacen_desguace_plano_nombre_check
    check (tipo <> 'zona_suelo' or nullif(btrim(nombre), '') is not null),
  constraint almacen_desguace_plano_geometria_check
    check (
      x between 0 and 1200 and y between 0 and 1500
      and ancho between 40 and 600 and alto between 30 and 500
      and rotacion in (0, 90)
    ),
  constraint almacen_desguace_plano_color_check
    check (color ~ '^#[0-9A-Fa-f]{6}$')
);

create unique index if not exists almacen_desguace_plano_estanteria_unica_idx
  on public.almacen_desguace_plano_elementos (codigo_estanteria)
  where tipo = 'estanteria';

drop trigger if exists almacen_desguace_plano_elementos_updated_at
  on public.almacen_desguace_plano_elementos;
create trigger almacen_desguace_plano_elementos_updated_at
before update on public.almacen_desguace_plano_elementos
for each row execute function public.almacen_desguace_set_updated_at();

alter table public.almacen_desguace_plano_elementos enable row level security;

drop policy if exists "API desguace plano elementos" on public.almacen_desguace_plano_elementos;
create policy "API desguace plano elementos" on public.almacen_desguace_plano_elementos
  for all to anon, authenticated using (true) with check (true);

grant select, insert, update, delete on public.almacen_desguace_plano_elementos to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_plano_elementos_id_seq to anon, authenticated;

create or replace function public.almacen_desguace_guardar_plano(elementos jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if jsonb_typeof(elementos) <> 'array' or jsonb_array_length(elementos) > 100 then
    raise exception 'La distribución del plano no es válida.';
  end if;

  -- La condición explícita mantiene compatibilidad con instalaciones que
  -- bloquean DELETE sin WHERE como medida de seguridad.
  delete from public.almacen_desguace_plano_elementos
  where id is not null;

  insert into public.almacen_desguace_plano_elementos (
    tipo, codigo_estanteria, nombre, x, y, ancho, alto, rotacion, color, orden
  )
  select
    item.tipo,
    nullif(item.codigo_estanteria, ''),
    coalesce(item.nombre, ''),
    item.x,
    item.y,
    item.ancho,
    item.alto,
    item.rotacion,
    item.color,
    item.orden
  from jsonb_to_recordset(elementos) as item(
    tipo text,
    codigo_estanteria text,
    nombre text,
    x numeric,
    y numeric,
    ancho numeric,
    alto numeric,
    rotacion integer,
    color text,
    orden integer
  );
end;
$$;

revoke all on function public.almacen_desguace_guardar_plano(jsonb) from public;
grant execute on function public.almacen_desguace_guardar_plano(jsonb) to anon, authenticated;

comment on table public.almacen_desguace_plano_elementos is
  'Posiciones visuales del plano. No altera las ubicaciones reales de piezas o cajones.';

notify pgrst, 'reload schema';
