-- Auditoría completa del Almacén Desguace.
-- Conserva los historiales de ubicaciones y cajones existentes.

create table if not exists public.almacen_desguace_eventos (
  id bigint generated by default as identity primary key,
  pieza_id bigint references public.almacen_desguace_piezas(id) on delete set null,
  pieza_codigo text not null,
  pieza_nombre text,
  cajon_id bigint references public.almacen_desguace_cajones(id) on delete set null,
  tipo_evento text not null,
  accion text not null,
  campos_cambiados text[] not null default '{}',
  valor_anterior jsonb,
  valor_nuevo jsonb,
  exito boolean not null default true,
  detalle text,
  error text,
  origen text not null default 'app',
  usuario_nombre text not null default 'Usuario de almacén',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint almacen_desguace_eventos_tipo_check check (
    tipo_evento in (
      'creacion_pieza', 'edicion_pieza', 'eliminacion_pieza',
      'cambio_estado', 'cambio_proceso', 'cambio_ubicacion',
      'cambio_cajon', 'cambio_online', 'foto',
      'publicacion_rf', 'online_manual'
    )
  )
);

create index if not exists almacen_desguace_eventos_fecha_idx
  on public.almacen_desguace_eventos (created_at desc);
create index if not exists almacen_desguace_eventos_pieza_idx
  on public.almacen_desguace_eventos (pieza_id, created_at desc);
create index if not exists almacen_desguace_eventos_codigo_idx
  on public.almacen_desguace_eventos (pieza_codigo, created_at desc);
create index if not exists almacen_desguace_eventos_tipo_idx
  on public.almacen_desguace_eventos (tipo_evento, created_at desc);

create or replace function public.almacen_desguace_auditar_pieza()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  campos text[];
  tipo text;
  accion_evento text;
begin
  if tg_op = 'INSERT' then
    insert into public.almacen_desguace_eventos (
      pieza_id, pieza_codigo, pieza_nombre, cajon_id, tipo_evento,
      accion, campos_cambiados, valor_nuevo, detalle, origen
    ) values (
      new.id, new.codigo_interno, new.nombre_pieza, new.cajon_id,
      'creacion_pieza', 'Pieza registrada',
      array(select jsonb_object_keys(to_jsonb(new) - array['id', 'created_at', 'updated_at'])),
      to_jsonb(new), 'Alta de la pieza en Almacén Desguace', 'base de datos'
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    insert into public.almacen_desguace_eventos (
      pieza_id, pieza_codigo, pieza_nombre, cajon_id, tipo_evento,
      accion, campos_cambiados, valor_anterior, detalle, origen
    ) values (
      old.id, old.codigo_interno, old.nombre_pieza, old.cajon_id,
      'eliminacion_pieza', 'Pieza eliminada',
      array(select jsonb_object_keys(to_jsonb(old) - array['id', 'created_at', 'updated_at'])),
      to_jsonb(old), 'Eliminación de la pieza', 'base de datos'
    );
    return old;
  end if;

  select coalesce(array_agg(campo order by campo), '{}'::text[])
  into campos
  from (
    select key as campo
    from jsonb_each(to_jsonb(new) - array['updated_at']) as actual
    where (to_jsonb(old) -> actual.key) is distinct from actual.value
  ) diferencias;

  if cardinality(campos) = 0 then
    return new;
  end if;

  if 'estado_proceso' = any(campos) then
    tipo := 'cambio_proceso';
    accion_evento := case when array_length(campos, 1) > 1 then 'Proceso y datos asociados cambiados' else 'Proceso cambiado' end;
  elsif 'estado_pieza' = any(campos) then
    tipo := 'cambio_estado';
    accion_evento := case when array_length(campos, 1) > 1 then 'Estado y datos asociados cambiados' else 'Estado de la pieza cambiado' end;
  elsif 'publicado_online' = any(campos) then
    tipo := 'cambio_online';
    accion_evento := case when array_length(campos, 1) > 1 then 'Online y datos asociados cambiados' else 'Estado Online cambiado' end;
  elsif 'cajon_id' = any(campos) then
    tipo := 'cambio_cajon';
    accion_evento := case when array_length(campos, 1) > 1 then 'Cajón y ubicación cambiados' else 'Cajón cambiado' end;
  elsif 'ubicacion' = any(campos) then
    tipo := 'cambio_ubicacion';
    accion_evento := 'Ubicación cambiada';
  elsif array_length(campos, 1) > 1 then
    tipo := 'edicion_pieza';
    accion_evento := 'Varios datos modificados';
  else
    tipo := 'edicion_pieza';
    accion_evento := 'Datos de la pieza modificados';
  end if;

  insert into public.almacen_desguace_eventos (
    pieza_id, pieza_codigo, pieza_nombre, cajon_id, tipo_evento,
    accion, campos_cambiados, valor_anterior, valor_nuevo, detalle, origen
  ) values (
    new.id, new.codigo_interno, new.nombre_pieza, new.cajon_id,
    tipo, accion_evento, campos, to_jsonb(old), to_jsonb(new),
    'Campos modificados: ' || array_to_string(campos, ', '), 'base de datos'
  );

  return new;
end;
$$;

drop trigger if exists almacen_desguace_auditar_pieza_cambios
  on public.almacen_desguace_piezas;
create trigger almacen_desguace_auditar_pieza_cambios
after insert or update on public.almacen_desguace_piezas
for each row execute function public.almacen_desguace_auditar_pieza();

drop trigger if exists almacen_desguace_auditar_pieza_eliminacion
  on public.almacen_desguace_piezas;
create trigger almacen_desguace_auditar_pieza_eliminacion
before delete on public.almacen_desguace_piezas
for each row execute function public.almacen_desguace_auditar_pieza();

-- Punto de partida para piezas que ya existían antes de activar la auditoría.
insert into public.almacen_desguace_eventos (
  pieza_id, pieza_codigo, pieza_nombre, cajon_id, tipo_evento,
  accion, campos_cambiados, valor_nuevo, detalle, origen, metadata
)
select
  pieza.id,
  pieza.codigo_interno,
  pieza.nombre_pieza,
  pieza.cajon_id,
  'edicion_pieza',
  'Estado inicial al activar el historial completo',
  array(select jsonb_object_keys(to_jsonb(pieza) - array['id', 'created_at', 'updated_at'])),
  to_jsonb(pieza),
  'Instantánea inicial. Los cambios anteriores a esta migración no pueden reconstruirse.',
  'migracion',
  '{"estado_inicial": true}'::jsonb
from public.almacen_desguace_piezas pieza
where not exists (
  select 1 from public.almacen_desguace_eventos evento
  where evento.pieza_id = pieza.id and evento.metadata @> '{"estado_inicial": true}'::jsonb
);

create or replace function public.almacen_desguace_auditar_foto()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  id_pieza bigint;
  codigo text;
  nombre text;
  accion_evento text;
begin
  id_pieza := case when tg_op = 'DELETE' then old.pieza_id else new.pieza_id end;
  select codigo_interno, nombre_pieza into codigo, nombre
  from public.almacen_desguace_piezas where id = id_pieza;

  if codigo is null then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  accion_evento := case
    when tg_op = 'INSERT' then 'Foto añadida'
    when tg_op = 'DELETE' then 'Foto eliminada'
    else 'Foto modificada'
  end;

  insert into public.almacen_desguace_eventos (
    pieza_id, pieza_codigo, pieza_nombre, tipo_evento, accion,
    campos_cambiados, valor_anterior, valor_nuevo, detalle, origen
  ) values (
    id_pieza, codigo, nombre, 'foto', accion_evento,
    array['fotos'],
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end,
    accion_evento || ' en la ficha de la pieza', 'base de datos'
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists almacen_desguace_auditar_fotos
  on public.almacen_desguace_fotos;
create trigger almacen_desguace_auditar_fotos
after insert or update or delete on public.almacen_desguace_fotos
for each row execute function public.almacen_desguace_auditar_foto();

alter table public.almacen_desguace_eventos enable row level security;

drop policy if exists "API desguace eventos" on public.almacen_desguace_eventos;
create policy "API desguace eventos" on public.almacen_desguace_eventos
  for all to anon, authenticated using (true) with check (true);

grant select, insert on public.almacen_desguace_eventos to anon, authenticated;
grant usage, select on sequence public.almacen_desguace_eventos_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
