-- Sesiones persistentes para comprobar físicamente las herramientas del taller.
create table if not exists public.herramientas_comunes_inventarios (
  id bigint generated by default as identity primary key,
  estado text not null default 'abierto' check (estado in ('abierto', 'finalizado', 'cancelado')),
  creado_por text not null,
  iniciado_at timestamptz not null default now(),
  finalizado_at timestamptz,
  finalizado_por text,
  total_esperadas integer not null default 0,
  total_presentes integer not null default 0,
  total_no_encontradas integer not null default 0,
  total_excluidas integer not null default 0
);

create unique index if not exists herramientas_comunes_un_inventario_abierto_uidx
  on public.herramientas_comunes_inventarios (estado)
  where estado = 'abierto';

create table if not exists public.herramientas_comunes_inventario_items (
  inventario_id bigint not null references public.herramientas_comunes_inventarios(id) on delete cascade,
  herramienta_id bigint not null references public.herramientas_comunes_herramientas(id) on delete restrict,
  codigo text not null,
  nombre text not null,
  qr_token uuid,
  foto_url text,
  ubicacion_esperada text,
  estado_anterior text not null,
  resultado text not null default 'pendiente' check (resultado in ('pendiente', 'presente', 'no_encontrada', 'excluida')),
  comprobada_at timestamptz,
  comprobada_por text,
  primary key (inventario_id, herramienta_id)
);

create index if not exists herramientas_comunes_inventario_items_resultado_idx
  on public.herramientas_comunes_inventario_items (inventario_id, resultado, nombre);

create or replace function public.herramientas_comunes_iniciar_inventario(p_empleado text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inventario public.herramientas_comunes_inventarios%rowtype;
  empleado_limpio text := nullif(btrim(coalesce(p_empleado, '')), '');
begin
  if empleado_limpio is null then raise exception 'No se ha identificado al administrador.'; end if;

  select * into inventario from public.herramientas_comunes_inventarios
  where estado = 'abierto' order by id desc limit 1;
  if found then return to_jsonb(inventario); end if;

  insert into public.herramientas_comunes_inventarios (creado_por)
  values (empleado_limpio) returning * into inventario;

  insert into public.herramientas_comunes_inventario_items
    (inventario_id, herramienta_id, codigo, nombre, qr_token, foto_url, ubicacion_esperada, estado_anterior)
  select inventario.id, herramienta.id, herramienta.codigo, herramienta.nombre, herramienta.qr_token, herramienta.foto_url,
    case
      when herramienta.estanteria_id is null then 'Sin ubicación asignada'
      else concat_ws(' · ', estanteria.zona, estanteria.codigo, 'Nivel ' || herramienta.nivel, herramienta.posicion)
    end,
    herramienta.estado
  from public.herramientas_comunes_herramientas herramienta
  left join public.herramientas_comunes_estanterias estanteria on estanteria.id = herramienta.estanteria_id
  where not herramienta.archivada and herramienta.estado <> 'prestada';

  update public.herramientas_comunes_inventarios
  set total_esperadas = (select count(*) from public.herramientas_comunes_inventario_items where inventario_id = inventario.id)
  where id = inventario.id returning * into inventario;
  return to_jsonb(inventario);
end;
$$;

create or replace function public.herramientas_comunes_comprobar_inventario(
  p_inventario_id bigint,
  p_herramienta_id bigint,
  p_empleado text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inventario public.herramientas_comunes_inventarios%rowtype;
  item public.herramientas_comunes_inventario_items%rowtype;
  empleado_limpio text := nullif(btrim(coalesce(p_empleado, '')), '');
begin
  select * into inventario from public.herramientas_comunes_inventarios
  where id = p_inventario_id for update;
  if not found or inventario.estado <> 'abierto' then raise exception 'Este inventario ya no está abierto.'; end if;

  update public.herramientas_comunes_inventario_items
  set resultado = 'presente', comprobada_at = now(), comprobada_por = empleado_limpio
  where inventario_id = inventario.id and herramienta_id = p_herramienta_id
  returning * into item;
  if not found then raise exception 'Esta herramienta no forma parte del inventario. Puede estar prestada o archivada.'; end if;

  update public.herramientas_comunes_inventarios
  set total_presentes = (select count(*) from public.herramientas_comunes_inventario_items where inventario_id = inventario.id and resultado = 'presente')
  where id = inventario.id;
  return to_jsonb(item);
end;
$$;

create or replace function public.herramientas_comunes_finalizar_inventario(
  p_inventario_id bigint,
  p_empleado text,
  p_marcar_no_encontradas boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inventario public.herramientas_comunes_inventarios%rowtype;
  empleado_limpio text := nullif(btrim(coalesce(p_empleado, '')), '');
begin
  select * into inventario from public.herramientas_comunes_inventarios
  where id = p_inventario_id for update;
  if not found or inventario.estado <> 'abierto' then raise exception 'Este inventario ya no está abierto.'; end if;

  update public.herramientas_comunes_inventario_items item
  set resultado = 'excluida'
  from public.herramientas_comunes_herramientas herramienta
  where item.inventario_id = inventario.id and item.resultado = 'pendiente'
    and item.herramienta_id = herramienta.id
    and (herramienta.estado = 'prestada' or herramienta.archivada);

  update public.herramientas_comunes_inventario_items
  set resultado = 'no_encontrada'
  where inventario_id = inventario.id and resultado = 'pendiente';

  if p_marcar_no_encontradas then
    insert into public.herramientas_comunes_movimientos
      (herramienta_id, tipo, empleado, estado_anterior, estado_nuevo, detalle)
    select herramienta.id, 'cambio_estado', empleado_limpio, herramienta.estado, 'disponible',
      'Herramienta localizada durante el inventario #' || inventario.id || '.'
    from public.herramientas_comunes_herramientas herramienta
    join public.herramientas_comunes_inventario_items item on item.herramienta_id = herramienta.id
    where item.inventario_id = inventario.id and item.resultado = 'presente'
      and herramienta.estado = 'perdida' and not herramienta.archivada;

    update public.herramientas_comunes_herramientas herramienta
    set estado = 'disponible', empleado_actual = null, vehiculo_actual = null, retirada_at = null
    from public.herramientas_comunes_inventario_items item
    where item.inventario_id = inventario.id and item.resultado = 'presente'
      and item.herramienta_id = herramienta.id and herramienta.estado = 'perdida' and not herramienta.archivada;

    insert into public.herramientas_comunes_movimientos
      (herramienta_id, tipo, empleado, estado_anterior, estado_nuevo, detalle)
    select herramienta.id, 'cambio_estado', empleado_limpio, herramienta.estado, 'perdida',
      'No encontrada al finalizar el inventario #' || inventario.id || '.'
    from public.herramientas_comunes_herramientas herramienta
    join public.herramientas_comunes_inventario_items item on item.herramienta_id = herramienta.id
    where item.inventario_id = inventario.id and item.resultado = 'no_encontrada'
      and not herramienta.archivada and herramienta.estado not in ('prestada', 'perdida');

    update public.herramientas_comunes_herramientas herramienta
    set estado = 'perdida', empleado_actual = null, vehiculo_actual = null, retirada_at = null
    from public.herramientas_comunes_inventario_items item
    where item.inventario_id = inventario.id and item.resultado = 'no_encontrada'
      and item.herramienta_id = herramienta.id and not herramienta.archivada and herramienta.estado <> 'prestada';
  end if;

  update public.herramientas_comunes_inventarios
  set estado = 'finalizado', finalizado_at = now(), finalizado_por = empleado_limpio,
      total_presentes = (select count(*) from public.herramientas_comunes_inventario_items where inventario_id = inventario.id and resultado = 'presente'),
      total_no_encontradas = (select count(*) from public.herramientas_comunes_inventario_items where inventario_id = inventario.id and resultado = 'no_encontrada'),
      total_excluidas = (select count(*) from public.herramientas_comunes_inventario_items where inventario_id = inventario.id and resultado = 'excluida')
  where id = inventario.id returning * into inventario;
  return to_jsonb(inventario);
end;
$$;

create or replace function public.herramientas_comunes_cancelar_inventario(p_inventario_id bigint, p_empleado text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare inventario public.herramientas_comunes_inventarios%rowtype;
begin
  update public.herramientas_comunes_inventarios
  set estado = 'cancelado', finalizado_at = now(), finalizado_por = nullif(btrim(coalesce(p_empleado, '')), '')
  where id = p_inventario_id and estado = 'abierto'
  returning * into inventario;
  if not found then raise exception 'Este inventario ya no está abierto.'; end if;
  return to_jsonb(inventario);
end;
$$;

revoke all on function public.herramientas_comunes_iniciar_inventario(text) from public, anon, authenticated;
revoke all on function public.herramientas_comunes_comprobar_inventario(bigint, bigint, text) from public, anon, authenticated;
revoke all on function public.herramientas_comunes_finalizar_inventario(bigint, text, boolean) from public, anon, authenticated;
revoke all on function public.herramientas_comunes_cancelar_inventario(bigint, text) from public, anon, authenticated;
grant execute on function public.herramientas_comunes_iniciar_inventario(text) to service_role;
grant execute on function public.herramientas_comunes_comprobar_inventario(bigint, bigint, text) to service_role;
grant execute on function public.herramientas_comunes_finalizar_inventario(bigint, text, boolean) to service_role;
grant execute on function public.herramientas_comunes_cancelar_inventario(bigint, text) to service_role;
